### PR TITLE
generate xml: Add generation of history metadata

### PR DESCRIPTION
**Pull request by ezhilsabareesh8**
This PR address #9

### CODE REVIEW

**Review by dougiesquire — CHANGES_REQUESTED** [review]
@ezhilsabareesh8 I think you might have accidentally committed the wrong file:
- we don't want `datm.streams.xml` in this repo
- you haven't committed changes to `generate_xml_datm.py`

**Comment by ezhilsabareesh8** [comment]
Apologise, I pushed the wrong file, added `generate_xml_datm.py` in this commit ee4b79b

**Review by dougiesquire — CHANGES_REQUESTED** [review]
Thanks @ezhilsabareesh8 - a couple of minor suggestions.

I regenerated the RYF streams with these changes and did a test run of `MOM6-CICE6` 11deg_jra55do_ryf`. Aside from revealing [this](https://github.com/COSIMA/om3-scripts/issues/16) bug (which we can address in a subsequent PR), this worked as expected.

**Review by dougiesquire — APPROVED** [review]
Thanks @ezhilsabareesh8. LGTM. By the way, you can just accept the suggestions in my review, rather than having to go and make the commits yourself

**Comment by dougiesquire** [comment]
> By the way, you can just accept the suggestions in my review, rather than having to go and make the commits yourself

My apologies - you did

**Pull request merged**
